### ISSUE TITLE
Provide a way to stop a GIF

### ISSUE THREAD

**Issue by alexiscreuzot** [wangjwchn/AImage#11]
In one of my previous PR I had put a `stopGIF()` function. This allows for `UIViewController` that stays in the view hierarchy. For instance in the case of an `UINavigationController` push, it allows to stop GIFs in the `viewDidDisappear`, which prevent undisplayed GIFs to hog on the CPU.

An even better way would be to automatically stop any GIF that is not displayed.

**Comment by wangjwchn** [comment]
Hi,@kirualex
This library already has automatically stop feature by judge function 'isDisplayedInScreen'.If the view is out of the screen.It will turn state 'display' to state 'suspended'(line 86 in JWAnimatedImageView).The problem is that it may not work in some cases.I'm still try to figure it out.It would be great if you test it on your APP.

**Comment by wangjwchn** [comment]
Hi,@kirualex
I think it's working now.You can have a test.
Notice that when cache.removeAllObjects() is executed,it will not be found at the 'Profile' from Xcode.
So you can test the memory usage by uncomment line 32 and 51 in JWAnimationManager.swift.
Another way to test whether the GIF is still displayed when an UINavigationController push, is checking the CPU usage at the 'Profile' from Xcode.But you have to make the  memoryLimit as little as possible.That makes the CPU usage change significantly.

**Comment by alexiscreuzot** [comment]
My app using a collection view doesn't work anymore with the current master branch.
The Gif is shown once, then reusing the cell and adding a new gif leaves a blank image...

**Comment by wangjwchn** [comment]
Hi,@kirualex
I tested this library in Apple official collection demo and [FruitsDiet APP](https://github.com/rshankras/FruitsDiet).It seems that everything is fine.
Could you give me a simple demo in your forked repository that describe this situation?

**Comment by alexiscreuzot** [comment]
I'm gonna create a sample when I can, it may be a problem on my end.

**Comment by wangjwchn** [comment]
I'll try my best to dig into this bug.Don't worry,If it still doesn't work, I will discard the auto view management

**Comment by alexiscreuzot** [comment]
Here's the sample.
As you'll see, the GIF is stuck on the first image for some cells. 

The "blank image" I was referring to in my previous comment was probably because I was using a gif which has a transparent first image.

[JWAnimatedImage.zip](https://github.com/wangjwchn/JWAnimatedImage/files/191953/JWAnimatedImage.zip)

**Comment by wangjwchn** [comment]
Hi,@kirualex
The latest commit has fixed this problem.But 'release memory automatically when GIF is not displayed' doesn't work anymore.The causes of all the problems are due to function 'isDisplayedInScreen'.If it is over-judged,the GIF is stuck on the first image.If it is less-judged,the memory will not be released when display stops.

**Comment by wangjwchn** [comment]
Hi,@kirualex
I've written my code over again and tested on all samples I can get.I'm sure it is fine.

**Comment by alexiscreuzot** [comment]
:+1:  You rock @wangjwchn !
